name: test1

on:
  push:
    branches:
      - alexei/rec-269-github-action-to-trigger-deploys-to-staging

jobs:
  trigger-deployment:
    if: ${{ github.repository_owner == 'recallnet' }}
    name: Trigger deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RECALL_WORKFLOW_TRIGGER_APP_ID }}
          private-key: ${{ secrets.RECALL_WORKFLOW_TRIGGER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: competition-app-deployments

      - id: image-id
        run: |
          echo "image=textile/js-recall:sha-868c97a" >> $GITHUB_OUTPUT

      - name: Trigger deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'competition-app-deployments',
              workflow_id: 'update-docker-image.yml',
              ref: 'alexei/update-docker-image',
              inputs: {
                stage: 'staging',
                version: 'v0',
                image: '${{ steps.image-id.outputs.image }}',
              }
            });
